//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.Input = new HashSet<Input>();
            this.Output = new HashSet<Output>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int per_id { get; set; }
        [Required(ErrorMessage ="Pls Enter Name")]
        public string per_name { get; set; }
        [Required(ErrorMessage = "Pls Choose Gender")]
        public bool gender { get; set; }
        [Required(ErrorMessage = "Pls Enter Birth")]
        public System.DateTime per_birth { get; set; }
        [Required(ErrorMessage = "Pls Enter Address")]
        public string per_address { get; set; }
        [Required(ErrorMessage = "Pls Choose Country")]
        public int country_id { get; set; }
        [Required(ErrorMessage = "Pls Enter Phone")]
        public int per_phone { get; set; }
        [Required(ErrorMessage = "Pls Enter Email")]
        public string per_email { get; set; }
        [Required(ErrorMessage = "Pls Choose Department")]
        public int depart_id { get; set; }
        [Required(ErrorMessage = "Pls Choose Type")]
        public int type_id { get; set; }
        [Required(ErrorMessage = "Pls Enter Username")]
        public string per_username { get; set; }
        [Required(ErrorMessage = "Pls Enter Password")]
        public string per_password { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Input> Input { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Output> Output { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
